import { message } from 'antd';
import { getGoods } from '../services/goods';

export default {
  namespace: 'goods',

  state: {
    data: {
      results: [],
      count: 0,
    },
    goodsData: [
      {
        image: 'card-1.jpeg',
        title: '我们的田野，美丽地田野。',
        description: '碧绿的河水流过无边的稻田，无边的稻田，好像起伏的海面。',
        footerTitle: 'footer title',
        shop: '金挑喜选',
        images: ['card-1.jpeg', 'card-2.jpeg', 'card-3.jpeg'],
        goodsSn: 'SN0001',
        categoryName: '钻石',
        price: 1000,
        groupName: ['经典系列'],
      },
      {
        image: 'card-2.jpeg',
        title: '一江春水向东流',
        description: '问君能有几多愁，恰似一江春水向东流。',
        footerTitle: 'footer title',
        shop: '儋州金大福',
        images: ['card-2.jpeg', 'card-3.jpeg', 'card-4.jpeg'],
        goodsSn: 'SN0002',
        categoryName: '黄金',
        price: 1200,
      },
      {
        image: 'card-3.jpeg',
        title: '走在乡间的小路上',
        description: '噢，噢，噢，他们唱，还有一支短笛在吹响。',
        footerTitle: 'footer title',
        shop: '一品清源',
        images: ['card-3.jpeg', 'card-4.jpeg', 'card-5.jpeg'],
        goodsSn: 'SN0003',
        categoryName: '彩宝',
        price: 1380,
      },
      {
        image: 'card-4.jpeg',
        title: 'here is title',
        description: 'here is desc，Ba la Ba la Ba la Ba la Ba la Ba la Ba la Ba la Ba la Ba la Ba la ...',
        footerTitle: 'footer title',
        shop: '石头记',
        images: ['card-4.jpeg', 'card-5.jpeg', 'card-6.jpeg'],
        goodsSn: 'SN0004',
        categoryName: '银饰',
        price: 6800,
      },
      {
        image: 'card-5.jpeg',
        title: '热气球啊啊',
        description: 'here is desc，Ba la Ba la Ba la Ba la Ba la Ba la Ba la Ba la Ba la Ba la Ba la ...',
        footerTitle: 'footer title',
        shop: '钻石小鸟',
        images: ['card-5.jpeg', 'card-6.jpeg', 'card-1.jpeg'],
        goodsSn: 'SN0005',
        categoryName: '珍珠',
        price: 8900,
      },
      {
        image: 'card-6.jpeg',
        title: 'here is title',
        description: 'here is desc，Ba la Ba la Ba la Ba la Ba la Ba la Ba la Ba la Ba la Ba la Ba la ...',
        footerTitle: 'footer title',
        shop: '周生生',
        images: ['card-6.jpeg', 'card-1.jpeg', 'card-2.jpeg'],
        goodsSn: 'SN0006',
        categoryName: '砗磲',
        price: 12800,
      },
      {
        image: 'card-1.jpeg',
        title: '我们的田野，美丽地田野。',
        description: '碧绿的河水流过无边的稻田，无边的稻田，好像起伏的海面。',
        footerTitle: 'footer title',
        shop: '金挑喜选',
        images: ['card-1.jpeg', 'card-2.jpeg', 'card-3.jpeg'],
        goodsSn: 'SN0001',
        categoryName: '钻石',
        price: 1000,
        groupName: ['经典系列'],
      },
      {
        image: 'card-2.jpeg',
        title: '一江春水向东流',
        description: '问君能有几多愁，恰似一江春水向东流。',
        footerTitle: 'footer title',
        shop: '儋州金大福',
        images: ['card-2.jpeg', 'card-3.jpeg', 'card-4.jpeg'],
        goodsSn: 'SN0002',
        categoryName: '黄金',
        price: 1200,
      },
      {
        image: 'card-3.jpeg',
        title: '走在乡间的小路上',
        description: '噢，噢，噢，他们唱，还有一支短笛在吹响。',
        footerTitle: 'footer title',
        shop: '一品清源',
        images: ['card-3.jpeg', 'card-4.jpeg', 'card-5.jpeg'],
        goodsSn: 'SN0003',
        categoryName: '彩宝',
        price: 1380,
      },
      {
        image: 'card-4.jpeg',
        title: 'here is title',
        description: 'here is desc，Ba la Ba la Ba la Ba la Ba la Ba la Ba la Ba la Ba la Ba la Ba la ...',
        footerTitle: 'footer title',
        shop: '石头记',
        images: ['card-4.jpeg', 'card-5.jpeg', 'card-6.jpeg'],
        goodsSn: 'SN0004',
        categoryName: '银饰',
        price: 6800,
      },
      {
        image: 'card-5.jpeg',
        title: '热气球啊啊',
        description: 'here is desc，Ba la Ba la Ba la Ba la Ba la Ba la Ba la Ba la Ba la Ba la Ba la ...',
        footerTitle: 'footer title',
        shop: '钻石小鸟',
        images: ['card-5.jpeg', 'card-6.jpeg', 'card-1.jpeg'],
        goodsSn: 'SN0005',
        categoryName: '珍珠',
        price: 8900,
      },
      {
        image: 'card-6.jpeg',
        title: 'here is title',
        description: 'here is desc，Ba la Ba la Ba la Ba la Ba la Ba la Ba la Ba la Ba la Ba la Ba la ...',
        footerTitle: 'footer title',
        shop: '周生生',
        images: ['card-6.jpeg', 'card-1.jpeg', 'card-2.jpeg'],
        goodsSn: 'SN0006',
        categoryName: '砗磲',
        price: 12800,
      },
    ],
  },

  effects: {
    *fetchGoods({ payload }, { call, put }) {
      const respon = yield call(getGoods, payload);
      yield put({ type: 'changeGoods', payload: respon });
    },
  },

  reducers: {
    changeGoods(state, action) {
      return {
        ...state,
        data: action.payload,
      };
    },
  },
};
